### PR TITLE
Removing documentation from readme

### PR DESCRIPTION
**Pull request by leportella**
The docs on the README were not updated since now we are developing the website version. 

Removed the main configuration definition and left only the install, starproject and run. 

Added link to documentation.

### CODE REVIEW

**Comment by leportella** [comment]
Nice idea @nicoddemus !

I really like projects examples. We could actually create a bot example using bottery in another repo and then add it to the documentation. What do you think?

**Comment by nicoddemus** [comment]
> I really like projects examples. We could actually create a bot example using bottery in another repo and then add it to the documentation. What do you think?

Sounds good and we should definitely do it, but I still think we should have a simple example in the README; it doesn't need to be a complete example mind you, just a quick overview of an "echo bot" would be enough to give an idea of how the framework operates.

In fact, I would argue that a short example like this should be one of the first things users see: it helps to "catch the eye" to the meat of the matter. For example: [pytest-mock](https://github.com/pytest-dev/pytest-mock), right away you see an example on how to use it. Same with [pytest](https://github.com/pytest-dev/pytest), a short introduction and an example. Installation, configuration, how to setup a project should come next, and even then might be just one or two short paragraphs for TL;DR users, which can then refer to the documentation for more complete explanation and how-tos.

Of course this is my personal opinion, although I'm sure I've read these "README good practices" somewhere but can't find any reference to it right now.

**Comment by nicoddemus** [comment]
(sorry for the long text btw 😁)

**Comment by rougeth** [comment]
Like everything else, there's an awesome project about readmes: [awesome-readme](https://github.com/matiassingers/awesome-readme).

**Pull request merged**
