### PR TITLE
Increase coverage for bottery/app.py

### PR DESCRIPTION
**Pull request by kplaube**
As reported in #45, we have a coverage of `59%` of `app.py` file.

With this Pull Request, by mocking "external agents" (like an user Engine or the Event Loop), we'll be able to increase it to `98%`.

Unfortunately, I don't really know why Coverage is saying that lines `54->57` aren't covered... debugged the code and I'm sure that the process is passing through them.

Hope it helps :)

### CODE REVIEW

**Comment by rougeth** [comment]
Thank you very much @kplaube! I'm in BH for Python Brasil, so, probably not gonna have time to review your PR the way I should. @nicoddemus could you check this? I'll try to work tomorrow, but cannot promise that.

**Comment by nicoddemus** [comment]
@rougeth sure, will take a look later today when I get home. 👍

**Comment by nicoddemus** [comment]
Looks good @kplaube, thanks! I resolved the conflicts, as soon as it passes we can merge it.

**Comment by kplaube** [comment]
Awesome! Thanks, guys :)

**Pull request merged**
