### PR TITLE
WIP: Abstract bot response and add Keyboard stuff

### PR DESCRIPTION
**Pull request by guidiego**
This PR use #65 branch as base

Example:

```python
from bottery.conf.patterns import Pattern
from bottery.response import Response
from bottery.widget.telegram import telegram_response, reply_keyboard_markup

def pong(message):
    telegram_kb = reply_keyboard_markup([['First'], ['Second']])
    telegram = telegram_response(message.user.id, 'test', reply_markup=telegram_kb)

    return Response(telegram=telegram)

patterns = [
    Pattern('ping', pong),
]
```

Whats happen:

screen shot 2017-10-13 at 18 36 54

### CODE REVIEW

**Comment by guidiego** [comment]
@rougeth now CI are passing (I will add some tests), but if you want hangouts about where we could put these guys will be a pleasure help you in it :D But I think in one possibility something like:

```
  | - platform
     | - __init__.py 
     | - telegram
        | -  integration.py (or better name) // actual platform.telegram.py
        | -  widgets.py (or better name)
```

If we will leave response.py include all possibilities of response I believe that we can maintain it on `bottery.response`, but I can't any problem in run it into `bottery.platform`

OBS: I think that is an excellent idea to refactor the test folder structure :)

**Comment by rougeth** [comment]
@guidiego could you provide an example of how the user would use theses functions?

**Comment by rougeth** [comment]
I was thinking about first giving the user (if it wants to) complete control of data sent to Telegram API. This way,  we wouldn't need to create every widgets provided by the platforms but the user would be able to use them.

**Comment by guidiego** [comment]
@rougeth Widget is only factory functions to help you a construct api objects :) You can pass the data as a simple Dict inside Response(telegram=telegram) and will work fine haha I add the examples in the PR :D

**Comment by rougeth** [comment]
@guidiego we now have a way of adding parameters to Telegram API request, which was need to add keyboard support:

```
@telegram.keyboard([['First button'], ['Second buttton']])
async def view(message):
    ...
```
This feature isn't finished, I still need to organized better names/modules/packages, but I believe we have a good/simple api design here.

**Comment by guidiego** [comment]
Let me know if you need any kind of help @rougeth <3

tenor

**Pull request closed without merging**
